name: build & push
description: Build and deploy ETL

runs:
  using: composite
  steps:
    - name: Build 
      working-directory: ./
      shell: bash -leo pipefail {0}
      run: make build-image

    - uses: 'actions/checkout@v4'

    - name: Authenticate to Google Cloud
      id: 'auth'
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider
        service_account: ${{ env.SERVICE_ACCOUNT }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: 'latest'
        project_id: ${{ env.GCP_PROJECT_ID }}

    - name: Configure Docker to use gcloud as a credential helper
      shell: bash
      run: |
        gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

    - name: Push Docker Image
      shell: bash
      run: |
        echo "pushing ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ env.TAG }}"
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ env.TAG }}

    - name: deploy cron
      shell: bash 
      if: ${{ github.ref_name == 'main' }}
      run: |
        IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ env.TAG }}
        PROJECT_ID=${{ env.GCP_PROJECT_ID }}
        SERVICE_ACCOUNT=${{ env.SERVICE_ACCOUNT }}
        ./resources/scripts/update_cron.sh ./resources/cron.yml
