name: Deploy to Dev

on:
  push:
    branches:
      - dev
    paths:
      - "**"

jobs:
  ci:
    name: Run CI
    uses: ./.github/workflows/fn_ci.yml
    with:
      tag: ${{ github.sha }}-rc # rc = release candidate (to distinguish from prod images)
