name: Deploy to Prod

on:
  push:
    branches:
      - main
    paths:
      - "**"

jobs:
  ci:
    name: Run CI
    uses: ./.github/workflows/fn_ci.yml
    with:
      tag: ${{ github.sha }} # rc = release candidate (to distinguish from prod images)
